# Generated by Django 4.2.4 on 2023-09-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='core_articl_title_2488db_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content'], name='core_articl_content_87875e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='core_articl_author__e61453_idx'),
        ),
    ]
